# Site settings
title: Start earlier, Invest Smarter, Secure Your Retirement!
description: > # this means to ignore newlines until "baseurl:"
See why you should start saving earlier and smarter to secure your retirement.

# Build settings
name: Animesh Verma(av2354), Jia Ying Jin(jj2980), and Minsu Yeom(my2582)
markdown: kramdown
