# Site settings
#title: Start earlier, Invest Smarter, Secure Your Retirement!
description: EDAV Project, Fall 2018, Columbia University - Animesh Verma(av2354), Jia Ying Jin(jj2980), and Minsu Yeom(my2582)
show_downloads: false

# Build settings
name: Animesh Verma(av2354), Jia Ying Jin(jj2980), and Minsu Yeom(my2582)
markdown: kramdown
theme: jekyll-theme-leap-day
